// Save Asaase Yaa — verified seed dataset.
// Every record here was read from a published source and hand-geotagged.
// The crawler appends to this; it never overwrites records with "verified": true.

module.exports = [
  {
    id: "fc-2026-02-24-national-survey",
    date: "2026-02-24",
    category: "forest",
    title: "Satellite survey: 8,923.8 hectares of forest reserve mined out",
    place: "National — released in Accra",
    region: "National",
    lat: 5.6, lon: -0.19,
    summary: "A national remote-sensing verification by the Forestry Commission found 45 forest reserves and one national park impacted by illegal mining as of 31 December 2024 — an area the Commission compared to roughly 12,500 football pitches.",
    metrics: { hectares: 8923.8, reserves: 46 },
    source: { name: "Graphic Online", url: "https://www.graphic.com.gh/news/general-news/ghana-news-galamsey-destroys-9-000-hectares-of-forest-reserves-forestry-commission-research.html" },
    verified: true
  },
  {
    id: "fc-2026-03-04-military-withdrawal",
    date: "2026-03-04",
    category: "forest",
    title: "Forestry Commission says degradation accelerated after military pulled out",
    place: "Accra",
    region: "Greater Accra",
    lat: 5.6, lon: -0.19,
    summary: "Commission CEO Hugh Brown told journalists that 5,252.9 hectares were lost between 2021 and 2024, and linked the recent surge to the withdrawal of military support from anti-galamsey operations on 1 November, which left rapid response teams under-equipped.",
    metrics: { hectares: 5252.9 },
    source: { name: "Citi Newsroom", url: "https://citinewsroom.com/2026/03/galamsey-destroys-nearly-9000-hectares-of-forest-reserves-forestry-commission/" },
    verified: true
  },
  {
    id: "fr-oda-river",
    date: "2026-02-24",
    category: "forest",
    title: "Oda River Forest Reserve is the worst-hit reserve in the country",
    place: "Oda River Forest Reserve, Amansie",
    region: "Ashanti",
    lat: 6.35, lon: -1.95,
    summary: "2,654.8 hectares mined out — the single largest loss recorded in any Ghanaian forest reserve. The Oda River corridor remains an active mining front.",
    metrics: { hectares: 2654.8 },
    source: { name: "Graphic Online", url: "https://www.graphic.com.gh/news/general-news/ghana-news-galamsey-destroys-9-000-hectares-of-forest-reserves-forestry-commission-research.html" },
    verified: true
  },
  {
    id: "fr-upper-wassa",
    date: "2026-02-24",
    category: "forest",
    title: "Upper Wassa Forest Reserve: 1,660.4 hectares mined out",
    place: "Upper Wassa Forest Reserve",
    region: "Western",
    lat: 5.6, lon: -2.05,
    summary: "The second most degraded reserve nationally, sitting inside the Western Region's belt of eleven affected reserves.",
    metrics: { hectares: 1660.4 },
    source: { name: "Graphic Online", url: "https://www.graphic.com.gh/news/general-news/ghana-news-galamsey-destroys-9-000-hectares-of-forest-reserves-forestry-commission-research.html" },
    verified: true
  },
  {
    id: "fr-apamprama",
    date: "2026-02-24",
    category: "forest",
    title: "Apamprama Forest Reserve: 1,366.7 hectares mined out",
    place: "Apamprama Forest Reserve",
    region: "Ashanti",
    lat: 6.35, lon: -1.72,
    summary: "Third on the national list. Ashanti alone accounts for 4,948.9 hectares across thirteen reserves.",
    metrics: { hectares: 1366.7 },
    source: { name: "Graphic Online", url: "https://www.graphic.com.gh/news/general-news/ghana-news-galamsey-destroys-9-000-hectares-of-forest-reserves-forestry-commission-research.html" },
    verified: true
  },
  {
    id: "fr-western-north",
    date: "2026-02-24",
    category: "forest",
    title: "Western North: 2,195.7 hectares gone across twelve reserves",
    place: "Sefwi / Bibiani reserve belt",
    region: "Western North",
    lat: 6.3, lon: -2.45,
    summary: "The second hardest-hit region in the Forestry Commission survey, covering the Sefwi and Bibiani reserve cluster.",
    metrics: { hectares: 2195.7, reserves: 12 },
    source: { name: "Graphic Online", url: "https://www.graphic.com.gh/news/general-news/ghana-news-galamsey-destroys-9-000-hectares-of-forest-reserves-forestry-commission-research.html" },
    verified: true
  },
  {
    id: "fr-upper-east",
    date: "2026-02-24",
    category: "forest",
    title: "Upper East: 210.7 hectares lost in three reserves",
    place: "Talensi / Nangodi mining belt",
    region: "Upper East",
    lat: 10.72, lon: -0.72,
    summary: "Evidence that the mining front is no longer only a southern forest problem — the northern gold belt around Talensi is now registering reserve loss.",
    metrics: { hectares: 210.7, reserves: 3 },
    source: { name: "Graphic Online", url: "https://www.graphic.com.gh/news/general-news/ghana-news-galamsey-destroys-9-000-hectares-of-forest-reserves-forestry-commission-research.html" },
    verified: true
  },
  {
    id: "fr-bono",
    date: "2026-02-24",
    category: "forest",
    title: "Bono Region: 136.2 hectares lost in a single reserve",
    place: "Bono reserve belt near Sunyani",
    region: "Bono",
    lat: 7.34, lon: -2.33,
    summary: "One reserve carries the region's entire recorded loss in the Forestry Commission survey.",
    metrics: { hectares: 136.2, reserves: 1 },
    source: { name: "Graphic Online", url: "https://www.graphic.com.gh/news/general-news/ghana-news-galamsey-destroys-9-000-hectares-of-forest-reserves-forestry-commission-research.html" },
    verified: true
  },
  {
    id: "fr-eastern",
    date: "2026-02-24",
    category: "forest",
    title: "Eastern Region: 56.7 hectares across three reserves",
    place: "Atewa Range and Birim basin reserves",
    region: "Eastern",
    lat: 6.23, lon: -0.57,
    summary: "Small by area, high by stake — these reserves sit on the headwaters that feed the Birim and Densu.",
    metrics: { hectares: 56.7, reserves: 3 },
    source: { name: "Graphic Online", url: "https://www.graphic.com.gh/news/general-news/ghana-news-galamsey-destroys-9-000-hectares-of-forest-reserves-forestry-commission-research.html" },
    verified: true
  },
  {
    id: "fr-central",
    date: "2026-02-24",
    category: "forest",
    title: "Central Region: 44.7 hectares of reserve impacted",
    place: "Offin basin, near Dunkwa-on-Offin",
    region: "Central",
    lat: 5.96, lon: -1.78,
    summary: "Recorded in the same national verification exercise; the Offin corridor remains under pressure.",
    metrics: { hectares: 44.7 },
    source: { name: "Graphic Online", url: "https://www.graphic.com.gh/news/general-news/ghana-news-galamsey-destroys-9-000-hectares-of-forest-reserves-forestry-commission-research.html" },
    verified: true
  },
  {
    id: "fr-savannah",
    date: "2026-02-24",
    category: "forest",
    title: "Savannah Region: 29.5 hectares of reserve impacted",
    place: "Savannah reserve belt",
    region: "Savannah",
    lat: 9.08, lon: -1.82,
    summary: "The smallest regional figure in the survey, but the region has since reported active enforcement against excavator crews.",
    metrics: { hectares: 29.5 },
    source: { name: "Graphic Online", url: "https://www.graphic.com.gh/news/general-news/ghana-news-galamsey-destroys-9-000-hectares-of-forest-reserves-forestry-commission-research.html" },
    verified: true
  },
  {
    id: "rec-2026-02-05-nyankumase",
    date: "2026-02-05",
    category: "reclamation",
    title: "800 acres replanted with cassia and teak at Nyankumase",
    place: "Nyankumase, Manso Adubia, Amansie South",
    region: "Ashanti",
    lat: 6.15, lon: -1.98,
    summary: "Young cassia and teak now hold ground that illegal mining had stripped bare — the clearest reclamation result yet under the current anti-galamsey drive, and proof that recovery is possible where political will holds.",
    metrics: { acres: 800 },
    source: { name: "Ghanaian Times via AllAfrica", url: "https://allafrica.com/stories/202602050493.html" },
    verified: true
  },
  {
    id: "arr-2026-04-30-mpatasie",
    date: "2026-04-30",
    category: "arrest",
    title: "Night raid on the Oda River corridor: 8 arrested, 4 excavators seized",
    place: "Mpatasie and Odaho, Amansie West",
    region: "Ashanti",
    lat: 6.28, lon: -2.05,
    summary: "NAIMOS and the Blue Water Guards moved from the Manso Adubia base at 22:30 on intelligence about active mining on the Oda riverbank. Three of the four excavators had already had their control boards stripped out — a now-routine tactic to make seized machines worthless.",
    metrics: { arrests: 8, excavators: 4 },
    source: { name: "Ghana Peace Journal", url: "https://ghanapeacejournal.com/naimos-blue-water-guards-arrest-8-galamseyers-seize-4-excavators-at-mpatasie-odaho/" },
    verified: true
  },
  {
    id: "arr-2026-05-02-mankranso",
    date: "2026-05-02",
    category: "arrest",
    title: "Convoy blocked at Nyameadom: six held, including two foreign nationals",
    place: "Nyameadom, Mankranso, Ahafo Ano South",
    region: "Ashanti",
    lat: 6.8, lon: -2.05,
    summary: "A syndicate fleeing in three pickups was stopped without confrontation. They abandoned their excavator at the site. The River Mankran, once the water supply for the Mankranso area, was left polluted alongside large tracts of farmland.",
    metrics: { arrests: 6, excavators: 1 },
    source: { name: "Ghana Peace Journal", url: "https://ghanapeacejournal.com/naimos-arrests-6-galamseyers-4-ghanaians-2-foreign-nationals-in-asante-region/" },
    verified: true
  },
  {
    id: "arr-2026-03-25-naimos-quarterly",
    date: "2026-03-25",
    category: "arrest",
    title: "NAIMOS quarterly: 237 arrests, 94 excavators, 87.7% strike rate",
    place: "National — briefing in Accra",
    region: "National",
    lat: 5.6, lon: -0.19,
    summary: "Director of Operations Col. Dominic Buah said most of those arrested were foreign nationals. NAIMOS has begun working with GIISDEC to pull wrecked changfan metalwork out of the Ankobra and repurpose seized pumps through the Ministry of Agriculture.",
    metrics: { arrests: 237, excavators: 94 },
    source: { name: "Rainbow Radio", url: "https://rainbowradioonline.com/2026/03/25/galamsey-crackdown-naimos-seizes-94-excavators-and-arrests-237-in-nationwide-sweep/" },
    verified: true
  },
  {
    id: "pol-2026-07-16-half-year",
    date: "2026-07-16",
    category: "arrest",
    title: "Half-year enforcement figures: 200 operations, 207 arrests",
    place: "National — Ministry of Lands and Natural Resources",
    region: "National",
    lat: 5.6, lon: -0.19,
    summary: "Minister Emmanuel Armah-Kofi Buah reported that between January and June 2026 task forces arrested 161 Ghanaians and 46 foreign nationals, seized 78 excavators and immobilised 90 more, destroyed 2,800 changfan machines on river bodies and demolished 1,244 mining camp structures.",
    metrics: { arrests: 207, excavators: 78, changfan: 2800, structures: 1244 },
    source: { name: "The Sikaman Times", url: "https://sikamantimes.com/govt-reports-200-anti-galamsey-operations-207-arrests-in-first-half-of-2026/" },
    verified: true
  },
  {
    id: "arr-2026-06-25-savannah",
    date: "2026-06-25",
    category: "arrest",
    title: "Savannah Region confiscates at least 18 excavators",
    place: "Damongo and sites across Savannah Region",
    region: "Savannah",
    lat: 9.08, lon: -1.82,
    summary: "Regional Minister Salisu Be-Awuribe said the machines are now with security agencies and operations will continue. He drew the line clearly: small-scale mining is legal with a licence, environmental compliance, and distance from rivers, reserves and cocoa farms.",
    metrics: { excavators: 18 },
    source: { name: "GBC Ghana Online", url: "https://www.gbcghanaonline.com/general/at-least-18-excavators-seized-in-anti-galamsey-operations-savannah-regional-minister/2026/" },
    verified: true
  },
  {
    id: "wat-2026-02-24-birim-pilot",
    date: "2026-02-24",
    category: "water",
    title: "EPA trials ionic nano copper treatment on the Birim",
    place: "Birim River, Kibi",
    region: "Eastern",
    lat: 6.17, lon: -0.55,
    summary: "EPA chief executive Nana Ama Browne Klutse led a simulation applying a nano-liquid directly to the river surface, with the Ghana Standards Authority and Ghana Water Company. If validated, the agency plans to extend it to the Ankobra, Pra and Offin.",
    metrics: {},
    source: { name: "GhanaWeb", url: "https://www.ghanaweb.com/GhanaHomePage/NewsArchive/EPA-tryouts-ionic-nano-copper-technology-on-polluted-Birim-River-2023079" },
    verified: true
  },
  {
    id: "wat-2026-02-25-cost-per-km",
    date: "2026-02-25",
    category: "reclamation",
    title: "$200,000 to restore one kilometre of river",
    place: "Birim River pilot reach",
    region: "Eastern",
    lat: 6.09, lon: -0.72,
    summary: "The price tag on the Birim pilot, run with the Ghana Atomic Energy Commission, Water Resources Commission and GWCL. Analysts note the figure is dwarfed by the damage already done — and it sets the arithmetic for every kilometre still being mined.",
    metrics: { usdPerKm: 200000 },
    source: { name: "GBC Ghana Online", url: "https://www.gbcghanaonline.com/general/200000-spent-to-restore-1km-of-galamsey-polluted-river/2026/" },
    verified: true
  },
  {
    id: "arr-2026-07-09-abesewa",
    date: "2026-07-09",
    category: "arrest",
    title: "Whistleblower tip leads to six arrests in Abesewa Forest",
    place: "Abesewa Forest reserve",
    region: "Ashanti",
    lat: 6.55, lon: -1.68,
    summary: "Two excavators impounded after a coordinated swoop by NAIMOS and the Regional Security Liaison Secretariat. Ashanti Regional Minister Dr Frank Amoakohene urged the public to keep reporting, calling community tip-offs critical to protecting the reserves.",
    metrics: { arrests: 6, excavators: 2 },
    source: { name: "Opemsuo 104.7", url: "https://opemsuo.com/six-arrested-two-excavators-seized-in-galamsey-operation-at-abesewa-forest/" },
    verified: true
  },
  {
    id: "pol-2026-05-11-kobro",
    date: "2026-05-11",
    category: "policy",
    title: "Party executives accused of interfering after Kobro Forest raid",
    place: "Kobro Forest",
    region: "Ashanti",
    lat: 6.75, lon: -1.55,
    summary: "Reports allege that local NDC executives intervened over arrests and the confiscation of excavators following an anti-galamsey raid — the pattern of political protection that critics say blunts enforcement.",
    metrics: {},
    source: { name: "Adom Online", url: "https://www.adomonline.com/ndc-executives-allegedly-interfere-in-arrests-and-confiscation-of-excavators-after-kobro-forest-anti-galamsey-raid/" },
    verified: true
  },
  {
    id: "arr-2025-04-18-samreboi",
    date: "2025-04-18",
    category: "arrest",
    title: "Samreboi dawn operation: 26 arrested across six sites",
    place: "Samreboi, Aowin / Wassa Amenfi West",
    region: "Western North",
    lat: 5.65, lon: -2.55,
    summary: "A twelve-hour intelligence-led raid by police and the Forestry Commission on sites linked to Akonta Mining. Six Chinese, two Korean and eighteen Ghanaian nationals were held; eight excavators were hauled out and five more left behind for lack of transport. The case that followed ended in a conviction in July 2026.",
    metrics: { arrests: 26, excavators: 8 },
    source: { name: "GhanaWeb", url: "https://www.ghanaweb.com/blogs/rocky55/26-people-are-arrested-and-excavators-are-seized-during-a-police-and-forestry-commission-operation-on-Chairman-Wontumi-s-Galamsey-sites-10870" },
    verified: true
  },
  {
    id: "pro-2026-07-21-wontumi-samreboi",
    date: "2026-07-21",
    category: "prosecution",
    title: "Wontumi jailed 20 years over illegal mining at Samreboi",
    place: "High Court, Accra — concession at Samreboi",
    region: "Greater Accra",
    lat: 5.56, lon: -0.2,
    summary: "The High Court in Accra sentenced Bernard Antwi Boasiako, Ashanti Regional Chairman of the NPP and known as Chairman Wontumi, to 20 years for assigning mineral rights granted to his company Akonta Mining Limited to two individuals without the Lands Minister's approval. A second 20-year term followed for purposely facilitating an unlicensed mining operation on the Samreboi concession, contrary to section 99(2)(b) of the Minerals and Mining Act 2006 (Act 703) as amended in 2019. The trial ran over twelve months and follows the April 2025 raid on sites linked to the company.",
    metrics: { years: 20 },
    source: { name: "Graphic Online", url: "https://www.graphic.com.gh/news/general-news/full-judgement-why-wontumi-was-jailed-20-years-for-illegal-mining-in-samreboi.html" },
    archiveUrl: "https://web.archive.org/web/2/https://www.graphic.com.gh/news/general-news/full-judgement-why-wontumi-was-jailed-20-years-for-illegal-mining-in-samreboi.html",
    verified: true
  },
  {
    id: "wat-2026-05-04-turbidity",
    date: "2026-05-04",
    category: "water",
    title: "Intake readings of 12,000–14,000 NTU on five river basins",
    place: "Pra, Birim, Ankobra, Tano and Offin intakes",
    region: "National",
    lat: 5.55, lon: -1.5,
    summary: "Ghana Water Company logged turbidity between 12,000 and 14,000 NTU at intake points — against roughly 2,000 NTU that treatment plants were built to handle. Commentators warn the fight is losable on politics rather than technique, with enforcement applied selectively.",
    metrics: { ntuLow: 12000, ntuHigh: 14000 },
    source: { name: "Ghanaian Times", url: "https://ghanaiantimes.com.gh/is-the-galamsey-fight-winnable/" },
    verified: true
  },
  {
    id: "pol-2026-04-cape-three-points",
    date: "2026-04-15",
    category: "policy",
    title: "Cape Three Points crackdown shows the state still has reach",
    place: "Cape Three Points, Ahanta West",
    region: "Western",
    lat: 4.75, lon: -2.08,
    summary: "Cited alongside reclaimed forest reserves as evidence the state retains coercive capacity. The same commentary notes the administration has deployed task forces, repealed L.I. 2462, and introduced excavator tracking and satellite monitoring.",
    metrics: {},
    source: { name: "Ghanaian Times", url: "https://ghanaiantimes.com.gh/is-the-galamsey-fight-winnable/" },
    verified: true
  },
  {
    id: "wat-2024-cocoa-rivers",
    date: "2024-09-24",
    category: "water",
    title: "Cocoa collapse and contaminated rivers across the mining belt",
    place: "Pra, Ankobra, Oti, Offin and Birim basins",
    region: "National",
    lat: 6.0, lon: -1.9,
    summary: "Excavators and bulldozers have cut through forest, riverbed and farmland alike. Cocobod output stood at 429,323 tonnes — under 55% of seasonal expectation — with illegal mining the main cause. At Mankurom alone, more than 100,000 acres of cocoa were wiped out.",
    metrics: { cocoaTonnes: 429323, cocoaAcresLost: 100000 },
    source: { name: "Institute for Security Studies", url: "https://issafrica.org/iss-today/ghana-must-stop-galamsey-before-it-sinks-the-country" },
    verified: true
  },
  {
    id: "wat-water-share",
    date: "2025-06-01",
    category: "water",
    title: "About 60% of Ghana's water bodies now polluted",
    place: "National",
    region: "National",
    lat: 7.5, lon: -1.2,
    summary: "Mercury and cyanide used in unregulated mining have contaminated surface and groundwater. Research links exposure in mining communities to kidney failure, birth defects and cancer.",
    metrics: { pollutedShare: 60 },
    source: { name: "NCCE Ghana", url: "https://nccegh.org/news/the-hidden-costs-of-galamsey-infrastructure-and-environmental-degradation-in-ghana" },
    verified: true
  },
  {
    id: "pol-2024-penalties",
    date: "2024-07-01",
    category: "policy",
    title: "Parliament raises penalties for illegal mining",
    place: "Parliament House, Accra",
    region: "Greater Accra",
    lat: 5.56, lon: -0.2,
    summary: "Amendments passed in 2024 lengthened jail terms and increased fines. Since 2017, Operation Vanguard and successor task forces have seized and destroyed mining equipment — with mixed and often reversible results on the ground.",
    metrics: {},
    source: { name: "GBC Ghana Online", url: "https://www.gbcghanaonline.com/general/at-least-18-excavators-seized-in-anti-galamsey-operations-savannah-regional-minister/2026/" },
    verified: true
  }
];
